[colors.selection]
background = "#504945"
text = "#d5c4a1"

[font]
builtin_box_drawing = true
size = 13
offset.x = 0
offset.y = 6
glyph_offset.y = 1

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
opacity = 1.0
